#Your Workflow name
name: Deploy to heroku

#Run workflow on every push to main branch
on:
  push:
    branches: [main]


# Your workflow jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2

### IMPORTANT PART ###

      - name: Build, Push and Release a Docker container to Heroku. # Your costom step name
        uses: gonuit/heroku-docker-deploy@v1.3.3 # Github action name (leave it as it is)
        with:
          #Below you must provide  variable for your Heroku app.
          #The email address associated with your Heroku account.
          #If your don't want to uses heroku secrets(Which is recommeded) you can do:
          #email: My.email@example.com
          email: ${{ secrets.HEROKU_EMAIL }}

          #Heroku API key accociated with provided  user's email
          #API Key is available under your heroku account settings.
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

          #Name of the  heroku applicationto which  the build is to be sent.
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME}}

          # (Optional, default: "./")
          # Dockerfile directory.
          # For example, if you have a  Dockerfile in the root of your project
          dockerfile_directory: ./

          # (Optional, default: "Dockerfile")
          # Dockerfile name.
          dockerfile_name: Dockerfile

          #(Optional, default: "")
          #Additional options of docker build command
          docker_options: "--no-cache"


          # (Optional, Default: "web")
          # Select the process type for which  you want the docker container to
          # By default, this  argument is set to "web".
          # For more information look at https://devcenter.heroku.com/articles/process-model

          process_type: web 
          
### ⬆ IMPORTANT PART ⬆ ###


